# name: "quick_neat"
# description: "A Quick NEAT Run"

Target:
  target_path: quickstart_output

GraphDataConfiguration:
  graph:
    directed: False
    node_path: tests/resources/test_graphs/test_small_nodes.tsv
    edge_path: tests/resources/test_graphs/test_small_edges.tsv
    verbose: True
    nodes_column: "id"
    node_list_node_types_column: "category"
    default_node_type: "biolink:NamedThing"
    sources_column: "subject"
    destinations_column: "object"
    default_edge_type: "biolink:related_to"

EmbeddingsConfig:
  filename: quickstart_embedding.csv
  history_filename: quickstart_embedding_history.json
  node_embeddings_params:
    method_name: CBOW
    walk_length: 10
    batch_size: 128
    window_size: 4
    return_weight: 1.0
    explore_weight: 1.0
    iterations: 5
  tsne_filename: tsne_quickstart.png

ClassifierContainer:
  classifiers:
    - classifier_id: lr_1
      classifier_name: Logistic Regression
      classifier_type: sklearn.linear_model.LogisticRegression
      edge_method: Average
      outfile: "model_lr_quickstart"
      parameters:
        sklearn_params:
          random_state: 42
          max_iter: 100

ApplyTrainedModelsContainer:
  models:
    - model_id: lr_1
      node_types:
        source:
          - "biolink:Protein"
        destination:
          - "biolink:Protein"
      cutoff: 0.9
      outfile: lr_protein_predictions.tsv