
name: run tests
on: [push]
jobs:
  run-make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v2
        name: setup python
        with:
          python-version: 3.7
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cmake
          # pip install git+https://github.com/monarch-initiative/embiggen.git@develop -U
          pip install git+https://github.com/monarch-initiative/embiggen.git@c2a81bad4c95d8577e1763a08fc6e679af02a645 -U
          pip install .
          pip install pytest
          pip install --upgrade pytest
          pip install --upgrade mypy
          pip install --upgrade pylint
          pip install yamllint          
          pip install coveralls
          pip install pytest-cov
          pip install validate_version_code
          pip install codacy-coverage
          pip install parameterized 
      - name: run pytest
        run: |
          coverage erase
          pytest --cov=neat --cov-report xml:coverage.xml
          coverage combine --append || true
          coverage report
          coverage xml
      - name: run mypy
        run: mypy --strict-optional neat
      - name: run yamllint
        run: yamllint -d relaxed yaml_ml_instructions/*.yaml
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.NEAT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
